dubbo:
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: 19999
  registry:
    # 挂载到 Spring Cloud 注册中心
    #   The traditional Dubbo's registry also is supported
    #   address: zookeeper://127.0.0.1:2181
    address: spring-cloud://localhost
  cloud:
    # 用于服务消费方订阅服务提供方的应用名称的列表，若需订阅多应用，使用 "," 分割。 不推荐使用默认值为 "*"，它将订阅所有应用。
    subscribed-services: spring-cloud-alibaba-dubbo-server
  application:
    qos:
      port: 11999
      enable: true
      accept-foreign-ip: false

